// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
// This file is automatically generated from src/environments/.env by scripts/load-env.js
// All API keys are stored in .env and accessed by the backend server only
// To update values, edit src/environments/.env and run: node scripts/load-env.js
export const environment = {
  production: false,
  apiUrl: 'http://localhost:3000'
};
