const fs = require('fs');
const path = require('path');

// Read .env file
const envPath = path.join(__dirname, '../src/environments/.env');
const envContent = fs.readFileSync(envPath, 'utf8');

// Parse .env file
const envVars = {};
envContent.split('\n').forEach(line => {
  const trimmedLine = line.trim();
  if (trimmedLine && !trimmedLine.startsWith('#')) {
    const [key, ...valueParts] = trimmedLine.split('=');
    if (key && valueParts.length > 0) {
      envVars[key.trim()] = valueParts.join('=').trim();
    }
  }
});

// Generate environment.ts - only apiUrl needed, all API keys are in .env and accessed by backend
const envTsContent = `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
// This file is automatically generated from src/environments/.env by scripts/load-env.js
// All API keys are stored in .env and accessed by the backend server only
// To update values, edit src/environments/.env and run: node scripts/load-env.js
export const environment = {
  production: false,
  apiUrl: '${envVars.API_URL || 'http://localhost:3000'}'
};
`;

// Generate environment.prod.ts - only apiUrl needed, all API keys are in .env and accessed by backend
const envProdTsContent = `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
// This file is automatically generated from src/environments/.env by scripts/load-env.js
// All API keys are stored in .env and accessed by the backend server only
// To update values, edit src/environments/.env and run: node scripts/load-env.js
export const environment = {
  production: true,
  apiUrl: '${envVars.API_URL || 'http://localhost:3000'}'
};
`;

// Write environment files
fs.writeFileSync(
  path.join(__dirname, '../src/environments/environment.ts'),
  envTsContent
);

fs.writeFileSync(
  path.join(__dirname, '../src/environments/environment.prod.ts'),
  envProdTsContent
);

console.log('Environment files generated successfully!');

